### ISSUE TITLE
Shopping cart icon is missing on desktop size

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-santiago#102]
* [x] Shopping cart icon is missing on desktop size

![screen_shot_2017-01-30_at_13_43_51](https://cloud.githubusercontent.com/assets/13623224/22421992/c8976a96-e6f2-11e6-8d61-4bcdf3654f52.png)

**Comment by kaspar-naaber** [comment]
Fixed in the `2143_shopping_cart_render_event` branch.

**Comment by SSirjes** [comment]
* [ ] Shopping cart icon is missing on desktop size

**Comment by kaspar-naaber** [comment]
Happens in construction only.
