### ISSUE TITLE
Design editor > shopping cart text color should not binded

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-santiago#103]
* ~~Maybe it's not good idea if shopping cart text color is binded with design editor secondary color~~

![screen shot 2017-01-30 at 13 53 44](https://cloud.githubusercontent.com/assets/13623224/22422324/69df8798-e6f4-11e6-86a2-eb104f3235d0.png)

**Comment by kaspar-naaber** [comment]
Both the text and the background can be modified from the Design Editor so there are good chances to mess it up if user selects mismatching colors. I reduced the hover background opacity a bit to make it more readable.

**Comment by kaspar-naaber** [comment]
I tested it a bit more and decided to unbind hover styles.
