### ISSUE TITLE
Common and front page layout content area width difference 

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-santiago#115]
* [ ] ~~Should front and common page layout width have same content area width?~~

**_Front page_**
![screen shot 2017-01-31 at 10 45 45](https://cloud.githubusercontent.com/assets/13623224/22457847/76d559f6-e7a2-11e6-9aa6-92177e65d092.png)

**_Common page_**
![screen shot 2017-01-31 at 10 46 17](https://cloud.githubusercontent.com/assets/13623224/22457859/85bf1ea2-e7a2-11e6-9d01-37fcdd68e363.png)

**Comment by kaspar-naaber** [comment]
Yes, "Front page" should be wider.
