### ISSUE TITLE
Product layout title and h1 is binded

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-santiago#131]
* [x] Is this correct, that product title get's from design editor 'Title' styles?

![screen_shot_2017-02-03_at_14_49_30](https://cloud.githubusercontent.com/assets/13623224/22591996/37d66134-ea20-11e6-8b66-afeba2d12573.png)

**Comment by kaspar-naaber** [comment]
When I first binded them it made sense for me. But I guess you are right and tehy should be separated. I'll add additional controllers under "Product" for this element.
