### ISSUE TITLE
Adding image in header looks different in editmode and previewmode.

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-santiago#143]
In editmode it is 100% wide but in public view it is inline-block.

**Comment by kaspar-naaber** [comment]
- [x] Set header link to `display: block;`. It makes entire header area clickable in live mode but it adds better support for images in header.

**Comment by SSirjes** [comment]
* [ ] **Mobile header** > **image size in header looks different in editmode and previewmode**
Video: http://recordit.co/uP9f5hbZ0w
