### ISSUE TITLE
Product list > remove breadcrumbs from first item

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-santiago#147]
PR #206 
* [ ] **Remove from product listing view first level breadcrumb**

![screen_shot_2017-02-16_at_12_05_34](https://cloud.githubusercontent.com/assets/13623224/23016760/52f22276-f440-11e6-945f-bf12ff066dd4.png)

**Comment by kaspar-naaber** [comment]
- [ ] Align settings button with other items to center.
