### ISSUE TITLE
Header images do not scale in mobile view.

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-santiago#183]
Close #210 
# Steps to reproduce
1. Add image to header area.
2. Set it to the size that is NOT as wide as the entire content area (doesn't have `edy-positionable-container-maxwidth` class).
3. Resize the window to see the page as in the mobile viewport.

Image doesn't scale.

![aug-30-2017 11-14-20](https://user-images.githubusercontent.com/3191867/29862155-69173ef6-8d74-11e7-9a91-c6056d93fd18.gif)

# Task list
- [x] Make image scalable.

# Concerns
* Number of the menu items may vary (menu burger, language menu, search icon).
* Width of the menu items may vary (text-based language menu).

**Comment by kaspar-naaber** [comment]
Currently can be hotfixed by inserting this code at the beginning of the header title content area:

```
<!-- Hack to fix image scaling in mobile viewport. -->
<style>
  @media screen and (max-width: 640px) {
      .layout-header__title .image-container {
        width: auto !important;
      }
      .layout-header::before {
        background-color: transparent !important;  
      }  
  }
</style>
```

**Comment by siimha** [comment]
PR#197
