### ISSUE TITLE
Should headings font-size on small screen be smaller

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-santiago#71]
* [ ] Should headings (h1, h2, h3) font-size on small screen be smaller

![screen shot 2017-01-24 at 16 46 42](https://cloud.githubusercontent.com/assets/13623224/22251796/b9b6866c-e254-11e6-8960-e3c98cb2ab94.png)

**Comment by kaspar-naaber** [comment]
It gets a little bit smaller. I wouldn't change it more smaller.
