### ISSUE TITLE
Should link have text-decoration: underline?

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-santiago#75]
* [x] Should link have text-decoration: underline?

_Red link color is good, but also heading are with color red.
If link has color red and text-decoration=underline, then for user maby it is better to see, what is link_

![screen shot 2017-01-25 at 14 05 07](https://cloud.githubusercontent.com/assets/13623224/22290027/4c3bb612-e307-11e6-9961-9eea9ed336f7.png)

**Comment by kaspar-naaber** [comment]
In which content area that happens? A link to a website would be perfect.
