### ISSUE TITLE
Shopping cart and search icon overlap 

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-santiago#76]
* [ ] Shopping cart and search icon overlap 

_**Happens**: if site search is enabled_

![screen_shot_2017-01-25_at_14_29_30](https://cloud.githubusercontent.com/assets/13623224/22290696/1a9412f4-e30b-11e6-8e75-474c0c33faca.png)

**Comment by kaspar-naaber** [comment]
Fixed with modifing the looks of the mobile shopping cart button.
