### ISSUE TITLE
Shopping cart > My order > remove link alignment 

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-santiago#78]
* ~~Shopping cart > My order > remove link > should have alignment: right?~~

![screen_shot_2017-01-26_at_16_05_58](https://cloud.githubusercontent.com/assets/13623224/22334073/eb5edcc6-e3e1-11e6-978d-5d6ff3d7ac45.png)

**Comment by kaspar-naaber** [comment]
It shouldn't be aligned right but it shouldn't hyphenate also.
