### ISSUE TITLE
Should submenu have bit more padding-top on small screen

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-santiago#79]
* [ ] Should submenu have bit more padding-top on small screen?

![screen_shot_2017-01-26_at_16_15_54](https://cloud.githubusercontent.com/assets/13623224/22334540/d6dbb01a-e3e3-11e6-898c-9dc4c82ab79f.png)

**Comment by kaspar-naaber** [comment]
I guess it looks okay with header separator:
![screenshot 2017-01-27 15 38 19](https://cloud.githubusercontent.com/assets/3191867/22372650/a3b7e690-e4a6-11e6-926b-95a39d4c15bb.png)
