### ISSUE TITLE
Blog and news layout > top content area

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-santiago#80]
* ~~Maybe it would be better if top content area is default empty?~~

_Now it looks like this_
![screen shot 2017-01-26 at 16 41 38](https://cloud.githubusercontent.com/assets/13623224/22335190/5b72dc02-e3e6-11e6-87ab-930dcbe8f129.png)

**Comment by kaspar-naaber** [comment]
When you create a new blog page, then it is empty by default. If it has content in in on signup, then it is related to default content.
