### ISSUE TITLE
Blog and news layout > small screen header

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-santiago#81]
* [x] Maybe on small screen blog and news header should have some border bottom --> separate better header and content block?

_Like this, maybe?_

![screen shot 2017-01-26 at 16 47 51](https://cloud.githubusercontent.com/assets/13623224/22335616/0f74dbbe-e3e8-11e6-888d-115604e1754f.png)

**Comment by kaspar-naaber** [comment]
Looks good! 👍
