### ISSUE TITLE
Blog and news layout alignment

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-santiago#85]
* [x] On small screen everything except post title are aligned left. 
**Question**: should blog post title also have align: left on small screen.

![screen shot 2017-01-27 at 13 15 03](https://cloud.githubusercontent.com/assets/13623224/22369093/aeeacd0c-e492-11e6-98e4-8a84dcac0597.png)

**Comment by kaspar-naaber** [comment]
Done!
