### ISSUE TITLE
Product layout. Fixed width breaks product layout

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-santiago#87]
* [x] Fixed width breaks product layout. Edge case?

![screen shot 2017-01-27 at 13 56 30](https://cloud.githubusercontent.com/assets/13623224/22370374/d05fafe6-e499-11e6-99d4-9830a7347fbf.png)

**Comment by kaspar-naaber** [comment]
Not an edge case. :)

**Comment by SSirjes** [comment]
* [ ] fixed width has fixed bg-color

![screen shot 2017-01-30 at 13 15 07](https://cloud.githubusercontent.com/assets/13623224/22421177/aabd9364-e6ee-11e6-9b82-408e986bba02.png)
