### ISSUE TITLE
Language menu touch area is too small in mobile

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-santiago#92]
* [ ] Language menu touch area is too small in mobile

![screen shot 2017-01-29 at 18 42 35](https://cloud.githubusercontent.com/assets/13623224/22405990/2a4f933a-e653-11e6-84e8-eb266077b7ab.png)

**Comment by kaspar-naaber** [comment]
Adding more whitespace makes it ugly. Let's leave it that way at the moment. If it ever becomes a real problem for a real user then we'll discuss it again.
