### ISSUE TITLE
Design editor > mobile menu text color

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-santiago#93]
* [ ] Menu color should not apply for mobile menu text
_Maybe it's better if mobile menu is not bínded with design editor?_

![screen shot 2017-01-29 at 18 51 36](https://cloud.githubusercontent.com/assets/13623224/22406072/4d02eab6-e654-11e6-9de2-0bf2b61895d9.png)

**Comment by kaspar-naaber** [comment]
It make sense that mobile menu gets the same color as the main menu. Only size shouldn't apply.
