### ISSUE TITLE
Design editor > headings font size change on small screen

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-santiago#94]
* [ ] On small screen common .css file change design editor font-size. Is this ok?
Video, where headings font-size change on small screen: http://recordit.co/b7QzN5C13N

**Comment by kaspar-naaber** [comment]
Yeap!

At the moment Design Editor only focuses on desktop screen. Mobile screen optimizes the sizes for better readability. It uses as much as it can on mobile screen, for example color, font-weight etc, but user probably doesn't want a huge font size on mobile screen so this applies to desktop screen only. There are some other properties that apply only to desktop – for example text alignmen in some cases.
